# Generated by Django 5.0.3 on 2024-03-25 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasbor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rakbuku',
            old_name='lokasi',
            new_name='nama',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='nomor_anggota',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='tahun_terbit',
        ),
        migrations.RemoveField(
            model_name='penerbit',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='pengarang',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='rakbuku',
            name='keterangan',
        ),
        migrations.RemoveField(
            model_name='rakbuku',
            name='nomor_rak',
        ),
        migrations.AddField(
            model_name='buku',
            name='rak',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dasbor.rakbuku'),
        ),
        migrations.AlterField(
            model_name='buku',
            name='penerbit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dasbor.penerbit'),
        ),
        migrations.AlterField(
            model_name='buku',
            name='pengarang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dasbor.pengarang'),
        ),
    ]
